pwd /home/rleo/github/rleofield/backup_data/backup_data
20211202-2023
mv: Aufruf von stat für 'aa_*' nicht möglich: Datei oder Verzeichnis nicht gefunden
mv: Aufruf von stat für 'rr_*' nicht möglich: Datei oder Verzeichnis nicht gefunden
20211202-202333: create file 'main_lock'
sending incremental file list
rsync: mkdir "/home/user/Desktop/backup_messages_bbackup" failed: No such file or directory (2)
rsync error: error in file IO (code 11) at main.c(682) [Receiver=3.1.3]
chown: ungültiger Benutzer: »user:user“
20211202-202357: remove file 'main_lock'
